function [fitresult, gof] = createFit(V, T)
%CREATEFIT(V,T)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V
%      Y Output: T
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-May-2024 18:21:31


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( V, T );

% Set up fittype and options.
ft = fittype( {'(sin(x-pi))', '((x-10)^2)', '1'}, 'independent', 'x', 'dependent', 'y', 'coefficients', {'a', 'b', 'c'} );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'T vs. V', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel V
ylabel T
grid on


